import React, { createContext, useContext, useState, useEffect } from 'react';

interface LanguageContextType {
  language: 'fr' | 'en';
  setLanguage: (lang: 'fr' | 'en') => void;
  t: (key: string) => string;
}

const translations = {
  fr: {
    // Navigation
    'nav.discover': 'Découverte',
    'nav.feed': 'Fil d\'actualité',
    'nav.search': 'Recherche',
    'nav.journal': 'Journal de jeu',
    'nav.profile': 'Profil',
    'nav.premium': 'Premium',
    'nav.friends': 'Amis',
    'nav.follows': 'Follows',
    'nav.notifications': 'Notifications',
    'nav.settings': 'Paramètres',
    'nav.logout': 'Déconnexion',
    
    // Auth
    'auth.login': 'Se connecter',
    'auth.register': 'Créer un compte',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.username': 'Nom d\'utilisateur',
    'auth.confirmPassword': 'Confirmer le mot de passe',
    'auth.loginTitle': 'Connectez-vous à votre compte',
    'auth.registerTitle': 'Créez votre compte',
    'auth.noAccount': 'Pas encore de compte ?',
    'auth.hasAccount': 'Déjà un compte ?',
    'auth.connecting': 'Connexion...',
    'auth.creating': 'Création...',
    'auth.demoAccount': 'Compte de démonstration : utilisez n\'importe quel email/mot de passe',
    
    // Profile
    'profile.gamesPlayed': 'Jeux joués',
    'profile.gamesCompleted': 'Jeux terminés',
    'profile.favoriteGames': 'Jeux favoris',
    'profile.averageRating': 'Note moyenne',
    'profile.editProfile': 'Modifier le profil',
    'profile.addFriends': 'Ajouter des amis',
    'profile.recentActivity': 'Activité Récente',
    'profile.followers': 'abonnés',
    'profile.following': 'abonnements',
    'profile.memberSince': 'Membre depuis',
    'profile.lastSession': 'Dernière session:',
    'profile.genreBreakdown': 'Répartition par Genre',
    'profile.platformsUsed': 'Plateformes Utilisées',
    'profile.yearlyActivity': 'Activité Annuelle',
    'profile.top4': 'Top 4',
    
    // Profile Edit
    'profile.editTitle': 'Modifier le profil',
    'profile.personalizeProfile': 'Personnalisez votre profil gaming',
    'profile.profilePicture': 'Photo de profil',
    'profile.changePhoto': 'Changer la photo',
    'profile.chooseAvatar': 'Choisissez parmi nos avatars gaming',
    'profile.importImage': 'ou importez votre propre image',
    'profile.uploadImage': 'Importer une image',
    'profile.coverPhoto': 'Photo de couverture',
    'profile.uploadBanner': 'Importer une bannière',
    'profile.chooseTemplate': 'ou choisissez parmi nos modèles :',
    'profile.personalInfo': 'Informations personnelles',
    'profile.biography': 'Biographie',
    'profile.biographyPlaceholder': 'Parlez-nous de vos jeux préférés...',
    'profile.location': 'Localisation',
    'profile.locationPlaceholder': 'Votre ville ou région',
    'profile.customLists': 'Listes personnalisées',
    'profile.unlimitedLists': 'Illimité',
    'profile.newList': 'Nouvelle liste',
    'profile.listNamePlaceholder': 'Nom de la liste...',
    'profile.create': 'Créer',
    'profile.noCustomLists': 'Aucune liste personnalisée',
    'profile.createListsDesc': 'Créez des listes pour organiser vos jeux',
    'profile.preferences': 'Préférences',
    'profile.profilePrivacy': 'Confidentialité du profil',
    'profile.public': 'Public',
    'profile.friendsOnly': 'Amis seulement',
    'profile.private': 'Privé',
    'profile.language': 'Langue',
    'profile.emailNotifications': 'Recevoir les notifications par email',
    'profile.saveChanges': 'Sauvegarder les modifications',
    'profile.games': 'jeu',
    'profile.gamesPlural': 'jeux',
    'profile.completedGame': 'A terminé',
    'profile.addedToList': 'A ajouté',
    'profile.toList': 'à sa liste',
    'profile.daysAgo': 'Il y a',
    'profile.days': 'jours',
    'profile.rating': 'Note:',
    'profile.hideStats': 'Masquer les stats',
    'profile.showStats': 'Voir les stats',
    
    // Profile Edit
    'profileEdit.title': 'Modifier le profil',
    'profileEdit.subtitle': 'Personnalisez votre profil gaming',
    'profileEdit.profilePicture': 'Photo de profil',
    'profileEdit.changePhoto': 'Changer la photo',
    'profileEdit.chooseAvatar': 'Choisissez parmi nos avatars gaming',
    'profileEdit.importImage': 'ou importez votre propre image',
    'profileEdit.uploadImage': 'Importer une image',
    'profileEdit.coverPhoto': 'Photo de couverture',
    'profileEdit.uploadBanner': 'Importer une bannière',
    'profileEdit.chooseTemplate': 'ou choisissez parmi nos modèles :',
    'profileEdit.personalInfo': 'Informations personnelles',
    'profileEdit.biography': 'Biographie',
    'profileEdit.biographyPlaceholder': 'Parlez-nous de vos jeux préférés...',
    'profileEdit.location': 'Localisation',
    'profileEdit.locationPlaceholder': 'Votre ville ou région',
    'profileEdit.customLists': 'Listes personnalisées',
    'profileEdit.unlimitedLists': 'Illimité',
    'profileEdit.newList': 'Nouvelle liste',
    'profileEdit.listNamePlaceholder': 'Nom de la liste...',
    'profileEdit.create': 'Créer',
    'profileEdit.noCustomLists': 'Aucune liste personnalisée',
    'profileEdit.createListsDesc': 'Créez des listes pour organiser vos jeux',
    'profileEdit.preferences': 'Préférences',
    'profileEdit.profilePrivacy': 'Confidentialité du profil',
    'profileEdit.public': 'Public',
    'profileEdit.friendsOnly': 'Amis seulement',
    'profileEdit.private': 'Privé',
    'profileEdit.language': 'Langue',
    'profileEdit.emailNotifications': 'Recevoir les notifications par email',
    'profileEdit.saveChanges': 'Sauvegarder les modifications',
    
    // Journal
    'journal.title': 'Journal de jeu',
    'journal.all': 'Tous',
    'journal.playing': 'En cours',
    'journal.completed': 'Terminés',
    'journal.wishlist': 'Wishlist',
    'journal.abandoned': 'Abandonnés',
    'journal.onHold': 'En pause',
    'journal.statistics': 'Statistiques',
    'journal.addedOn': 'Ajouté le',
    'journal.lastSession': 'Dernière session',
    'journal.playtime': 'Temps de jeu',
    'journal.myRating': 'Ma note',
    'journal.myReview': 'Ma critique',
    'journal.noGamesFound': 'Aucun jeu trouvé',
    'journal.startAdding': 'Commencez à ajouter des jeux à votre collection !',
    'journal.gamesByYear': 'Jeux par Année de Sortie',
    'journal.genreBreakdown': 'Répartition par Genre',
    'journal.platformsUsed': 'Plateformes Utilisées',
    'journal.gameStatus': 'Statut des Jeux',
    'journal.ratingDistribution': 'Répartition des Notes',
    'journal.summary': 'Résumé',
    'journal.totalGames': 'Total des jeux',
    'journal.differentGenres': 'Genres différents',
    'journal.platformsUsedCount': 'Plateformes utilisées',
    'journal.gamesRated': 'Jeux notés',
    'journal.averageRating': 'Note moyenne',
    
    // Search
    'search.title': 'Recherche',
    'search.games': 'Jeux',
    'search.users': 'Utilisateurs',
    'search.searchGames': 'Rechercher un jeu, développeur, genre...',
    'search.searchUsers': 'Rechercher un utilisateur...',
    'search.filters': 'Filtres',
    'search.clearAll': 'Effacer tout',
    'search.relevance': 'Pertinence',
    'search.highestRated': 'Notes les plus élevées',
    'search.lowestRated': 'Notes les plus basses',
    'search.newest': 'Plus récents',
    'search.oldest': 'Plus anciens',
    'search.mostAnticipated': 'Les plus attendus',
    'search.publisher': 'Maison d\'édition',
    'search.gameType': 'Type de jeu',
    'search.releaseYear': 'Année de sortie',
    'search.playerCount': 'Nombre de joueurs',
    'search.userRatings': 'Notes utilisateurs',
    'search.results': 'Résultats',
    'search.noResults': 'Aucun résultat pour',
    'search.tryOtherKeywords': 'Essayez avec d\'autres mots-clés ou vérifiez l\'orthographe.',
    'search.modifyFilters': 'Essayez de modifier vos critères de recherche ou vos filtres.',
    'search.noUsersFound': 'Aucun utilisateur trouvé pour',
    'search.tryOtherUsers': 'Essayez avec d\'autres mots-clés ou parcourez les suggestions d\'amis.',
    'search.followers': 'abonnés',
    'search.following': 'abonnements',
    'search.gamesPlayed': 'jeux joués',
    
    // Feed
    'feed.title': 'Fil d\'actualité',
    'feed.friends': 'Amis',
    'feed.follows': 'Follows',
    'feed.trends': 'Tendances',
    'feed.recent': 'Plus récents',
    'feed.mostLiked': 'Les plus aimées',
    'feed.mostCommented': 'Les plus commentées',
    'feed.share': 'Partager',
    'feed.writeComment': 'Écrivez un commentaire...',
    'feed.comment': 'Commentaire',
    'feed.reply': 'Répondre',
    'feed.helpful': 'Utile',
    'feed.noActivity': 'Aucune activité récente',
    'feed.followMore': 'Suivez plus d\'amis pour voir leur activité ici !',
    'feed.noComments': 'Aucun commentaire pour le moment',
    'feed.ago': 'Il y a',
    'feed.hours': 'h',
    'feed.days': 'j',
    'feed.minutes': 'min',
    
    // Discover
    'discover.title': 'Découverte',
    'discover.topRated': 'Jeux les mieux notés',
    'discover.mostAnticipated': 'Jeux les plus attendus',
    'discover.recommended': 'Recommandés pour vous',
    'discover.upcoming': 'À venir',
    'discover.topPlayed': 'Top jeux les plus joués',
    'discover.goodRecommendation': 'Bonne recommandation',
    'discover.badRecommendation': 'Mauvaise recommandation',
    
    // Premium
    'premium.title': 'Factiony Premium',
    'premium.subtitle': 'Débloquez tout le potentiel de votre expérience gaming',
    'premium.price': '2,99€',
    'premium.perMonth': 'par mois (TVA comprise)',
    'premium.upgrade': 'Passer à Premium',
    'premium.referral': 'Programme de Parrainage',
    'premium.referralDesc': 'Invitez vos amis sur Factiony et recevez 1 mois Premium gratuit pour chaque groupe de 3 amis qui créent un compte !',
    'premium.whatYouGet': 'Que vous apporte Premium ?',
    'premium.detailedRating': 'Notation détaillée des jeux',
    'premium.detailedRatingDesc': 'Notez séparément le gameplay, les graphismes, l\'histoire et la musique',
    'premium.fullCustomization': 'Personnalisation complète du profil',
    'premium.fullCustomizationDesc': 'Photo de profil, bannière personnalisée et thèmes exclusifs',
    'premium.unlimitedLists': 'Listes illimitées',
    'premium.unlimitedListsDesc': 'Créez autant de listes que vous voulez (vs 2 sans Premium)',
    'premium.weeklyNewsletter': 'Newsletter hebdomadaire',
    'premium.weeklyNewsletterDesc': 'Recevez les dernières actualités gaming et recommandations personnalisées',
    'premium.supportBuff': 'Soutenez Factiony',
    'premium.supportBuffDesc': 'Aidez-nous à développer de nouvelles fonctionnalités et à faire grandir la communauté',
    'premium.adFree': 'Interface sans publicité',
    'premium.adFreeDesc': 'Profitez d\'une expérience pure sans interruption publicitaire',
    'premium.discordAccess': 'Accès Forum Premium',
    'premium.discordAccessDesc': 'Rejoignez notre forum exclusif et discutez avec d\'autres membres Premium',
    'premium.cancelAnytime': 'Annulable à tout moment',
    'premium.testimonials': 'Ce que disent nos utilisateurs Premium',
    'premium.testimonial1': 'Les listes illimitées ont changé ma façon d\'organiser ma collection. Je recommande !',
    'premium.testimonial2': 'La newsletter m\'aide à découvrir de nouveaux jeux chaque semaine. Parfait !',
    'premium.testimonialAuthor1': 'GameMaster92',
    'premium.testimonialAuthor2': 'ProGamer',
    'premium.finalizeSubscription': 'Finaliser votre abonnement',
    'premium.referralCode': 'Votre code de parrainage :',
    'premium.copy': 'Copier',
    'premium.summary': 'Récapitulatif',
    'premium.monthly': 'mensuel',
    'premium.total': 'Total',
    'premium.vatIncluded': 'TVA incluse',
    'premium.cardNumber': 'Numéro de carte',
    'premium.expiryDate': 'Date d\'expiration',
    'premium.cardName': 'Nom sur la carte',
    'premium.confirmPayment': 'Confirmer le paiement',
    'premium.securePayment': 'Paiement sécurisé. Annulable à tout moment depuis votre profil.',
    'premium.paymentSuccess': 'Paiement simulé réussi ! Bienvenue dans Factiony Premium 🎉',
    
    // Friends
    'friends.title': 'Ajouter des Amis',
    'friends.search': 'Rechercher par nom ou email',
    'friends.searchPlaceholder': 'Nom d\'utilisateur ou email...',
    'friends.invite': 'Inviter un Ami',
    'friends.inviteDesc': 'Partagez Factiony avec vos amis et gagnez 1 mois Premium gratuit pour chaque groupe de 3 amis !',
    'friends.referralCode': 'Votre code de parrainage :',
    'friends.copyLink': 'Copier le lien',
    'friends.sendInvite': 'Envoyer une invitation',
    'friends.follow': 'Suivre',
    'friends.following': 'Suivi',
    'friends.discoverFollow': 'Découvrez et suivez d\'autres gamers passionnés',
    'friends.referralBenefits': 'Avantages du parrainage',
    'friends.benefit1': '1 mois Premium gratuit pour vous (tous les 3 amis)',
    'friends.benefit2': '1 mois Premium gratuit pour votre ami',
    'friends.benefit3': 'Aidez Factiony à grandir',
    'friends.benefit4': 'Partagez votre passion du gaming',

    // Games
    'games.rating': 'Note',
    'games.platforms': 'Plateformes',
    'games.publisher': 'Éditeur',
    'games.votes': 'votes',
    'games.rateAndReview': 'Noter et commenter',
    'games.followGame': 'Suivre ce jeu',
    'games.yourRating': 'Votre note',
    'games.yourReview': 'Votre critique...',
    'games.publish': 'Publier',
    'games.buyGame': 'Acheter le jeu',
    'games.buyOn': 'Acheter sur',
    'games.userReviews': 'Critiques des utilisateurs',
    'games.masterpiece': 'Un chef-d\'œuvre absolu ! L\'histoire, les personnages, le monde ouvert... tout est parfait.',
    'games.agree': 'Totalement d\'accord ! Ce jeu est un chef-d\'œuvre.',

    // Notifications
    'notifications.title': 'Mes Notifications',
    'notifications.all': 'Toutes',
    'notifications.likes': 'Likes',
    'notifications.followers': 'Abonnés',
    'notifications.comments': 'Commentaires',
    'notifications.noNotifications': 'Aucune notification',
    'notifications.settings': 'Paramètres de Notification',
    'notifications.newFollowers': 'Nouveaux abonnés',
    'notifications.newFollowersDesc': 'Quand quelqu\'un vous suit',
    'notifications.likesOnReviews': 'Likes sur vos critiques',
    'notifications.likesOnReviewsDesc': 'Quand quelqu\'un aime vos critiques',
    'notifications.commentsDesc': 'Quand quelqu\'un commente vos critiques',
    'notifications.friendActivity': 'Activité des amis',
    'notifications.friendActivityDesc': 'Nouvelles critiques de vos abonnements',
    'notifications.gameReleases': 'Sorties de jeux',
    'notifications.gameReleasesDesc': 'Nouveaux jeux et mises à jour',
    'notifications.promotions': 'Promotions',
    'notifications.promotionsDesc': 'Offres spéciales et réductions',
    'notifications.method': 'Méthode de notification',
    'notifications.pushNotifications': 'Notifications push',
    'notifications.emailOnly': 'Email uniquement',

    // Account Settings
    'account.title': 'Paramètres du Compte',
    'account.username': 'Nom d\'utilisateur',
    'account.firstName': 'Prénom',
    'account.lastName': 'Nom',
    'account.bio': 'Biographie',
    'account.saveChanges': 'Sauvegarder les modifications',
    'account.security': 'Sécurité',
    'account.changePassword': 'Changer le mot de passe',
    'account.deleteAccount': 'Supprimer le compte',
    'account.updated': 'Informations mises à jour !',
    
    // Common
    'common.save': 'Sauvegarder',
    'common.cancel': 'Annuler',
    'common.copy': 'Copier',
    'common.search': 'Rechercher',
    'common.loading': 'Chargement...',
    'common.language': 'Langue',
    'common.french': 'Français',
    'common.english': 'English',
    'common.back': 'Retour',
    'common.continue': 'Continuer',
    'common.skip': 'Passer cette étape',
    'common.finish': 'Terminer',
    'common.copied': 'Copié !',
    'common.minimum': 'minimum',
    'common.total': 'Total',
    'common.post': 'Publier',
    'common.send': 'Envoyer',
    'common.reply': 'Répondre',
    'common.sending': 'Envoi...',
    'common.confirmDelete': 'Êtes-vous sûr de vouloir supprimer cet élément ?',
    'common.showReplies': 'Voir les réponses',
    'common.hideReplies': 'Masquer les réponses',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    
    // Game Detail Modal
    'game.overview': 'Aperçu',
    'game.reviews': 'Critiques',
    'game.forum': 'Forum',
    'game.description': 'Description',
    'game.screenshots': 'Captures d\'écran',
    'game.systemRequirements': 'Configuration requise',
    'game.minimum': 'Minimum',
    'game.recommended': 'Recommandé',
    'game.information': 'Informations',
    'game.developer': 'Développeur',
    'game.publisher': 'Éditeur',
    'game.releaseDate': 'Date de sortie',
    'game.platforms': 'Plateformes',
    'game.metacritic': 'Metacritic',
    'game.playtime': 'Temps de jeu',
    'game.mainStory': 'Histoire principale',
    'game.completionist': 'Complétionniste',
    'game.average': 'Moyenne',
    'game.buyGame': 'Acheter le jeu',
    'game.rateAndReview': 'Noter et commenter',
    'game.followGame': 'Suivre ce jeu',
    'game.followed': 'Suivi',
    'game.addSession': 'Ajouter une session',
    'game.userReviews': 'Critiques des utilisateurs',
    'game.noReviews': 'Aucune critique pour le moment',
    'game.writeReview': 'Écrire une critique',
    'game.trailers': 'Bandes-annonces',
    'game.trailer': 'Bande-annonce',
    'game.coming': 'À venir',
    'game.votes': 'votes',
    'game.anticipating': 'En attente',
    'game.anticipated': 'En attente',
    'game.anticipationCount': 'personnes en attente',
    'game.whyAnticipate': 'Pourquoi voulez-vous y jouer ?',
    'game.whyNotAnticipate': 'Pourquoi ne voulez-vous pas y jouer ?',
    'game.anticipationComment': 'Votre commentaire...',
    'game.wantToPlay': 'J\'ai hâte d\'y jouer',
    'game.dontWantToPlay': 'Je ne pense pas y jouer',
    'game.anticipationComments': 'Commentaires d\'anticipation',
    'game.forumDiscussion': 'Discussion',
    'game.askQuestion': 'Poser une question',
    'game.shareThoughts': 'Partager vos réflexions',
    'game.writeComment': 'Écrire un commentaire...',
    'game.sortBy': 'Trier par',
    'game.mostRecent': 'Plus récents',
    'game.mostPopular': 'Plus populaires',
    'game.mostLiked': 'Plus aimés',
    'game.reply': 'Répondre',
    'game.replies': 'réponses',
    'game.showReplies': 'Voir les réponses',
    'game.hideReplies': 'Masquer les réponses',
    'game.writeReply': 'Écrire une réponse...',
    'game.noForumPosts': 'Aucune discussion pour le moment',
    'game.startDiscussion': 'Soyez le premier à lancer la discussion !',
    
    // Review Modal
    'review.writeReview': 'Écrire une critique',
    'review.yourReview': 'Votre critique',
    'review.rating': 'Note',
    'review.notRated': 'Non noté',
    'review.quickReview': 'Critique express (note uniquement)',
    'review.shareExperience': 'Partagez votre expérience avec ce jeu...',
    'review.containsSpoilers': 'Cette critique contient des spoilers',
    'review.personalTags': 'Tags personnels',
    'review.addTag': 'Ajouter un tag...',
    'review.add': 'Ajouter',
    'review.cancel': 'Annuler',
    'review.publish': 'Publier la critique',
    'review.share': 'Partager',
    'review.shareReview': 'Partager la critique',
    'review.copyLink': 'Copier le lien',
    'review.copied': 'Copié !',
    'review.shareOn': 'Partager sur',
    
    // Game Session Modal
    'session.newSession': 'Nouvelle session de jeu',
    'session.date': 'Date',
    'session.duration': 'Durée (minutes)',
    'session.platform': 'Plateforme',
    'session.progress': 'Progression (%)',
    'session.personalNotes': 'Notes personnelles',
    'session.impressions': 'Vos impressions sur cette session...',
    'session.addScreenshots': 'Ajouter des captures',
    'session.save': 'Enregistrer',
    
    // Game Card
    'gameCard.addToList': 'Ajouter à la liste',
    'gameCard.removeFromList': 'Retirer de la liste'
  },
  en: {
    // Navigation
    'nav.discover': 'Discover',
    'nav.feed': 'Feed',
    'nav.search': 'Search',
    'nav.journal': 'Game Journal',
    'nav.profile': 'Profile',
    'nav.premium': 'Premium',
    'nav.friends': 'Friends',
    'nav.follows': 'Follows',
    'nav.notifications': 'Notifications',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    
    // Auth
    'auth.login': 'Sign In',
    'auth.register': 'Create Account',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.username': 'Username',
    'auth.confirmPassword': 'Confirm Password',
    'auth.loginTitle': 'Sign in to your account',
    'auth.registerTitle': 'Create your account',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.hasAccount': 'Already have an account?',
    'auth.connecting': 'Signing in...',
    'auth.creating': 'Creating account...',
    'auth.demoAccount': 'Demo account: use any email/password',
    
    // Profile
    'profile.gamesPlayed': 'Games Played',
    'profile.gamesCompleted': 'Games Completed',
    'profile.favoriteGames': 'Favorite Games',
    'profile.averageRating': 'Average Rating',
    'profile.editProfile': 'Edit Profile',
    'profile.addFriends': 'Add Friends',
    'profile.recentActivity': 'Recent Activity',
    'profile.followers': 'followers',
    'profile.following': 'following',
    'profile.memberSince': 'Member since',
    'profile.lastSession': 'Last session:',
    'profile.genreBreakdown': 'Genre Breakdown',
    'profile.platformsUsed': 'Platforms Used',
    'profile.yearlyActivity': 'Yearly Activity',
    'profile.top4': 'Top 4',
    
    // Profile Edit
    'profile.editTitle': 'Edit Profile',
    'profile.personalizeProfile': 'Personalize your gaming profile',
    'profile.profilePicture': 'Profile Picture',
    'profile.changePhoto': 'Change Photo',
    'profile.chooseAvatar': 'Choose from our gaming avatars',
    'profile.importImage': 'or import your own image',
    'profile.uploadImage': 'Upload Image',
    'profile.coverPhoto': 'Cover Photo',
    'profile.uploadBanner': 'Upload Banner',
    'profile.chooseTemplate': 'or choose from our templates:',
    'profile.personalInfo': 'Personal Information',
    'profile.biography': 'Biography',
    'profile.biographyPlaceholder': 'Tell us about your favorite games...',
    'profile.location': 'Location',
    'profile.locationPlaceholder': 'Your city or region',
    'profile.customLists': 'Custom Lists',
    'profile.unlimitedLists': 'Unlimited',
    'profile.newList': 'New List',
    'profile.listNamePlaceholder': 'List name...',
    'profile.create': 'Create',
    'profile.noCustomLists': 'No custom lists',
    'profile.createListsDesc': 'Create lists to organize your games',
    'profile.preferences': 'Preferences',
    'profile.profilePrivacy': 'Profile Privacy',
    'profile.public': 'Public',
    'profile.friendsOnly': 'Friends Only',
    'profile.private': 'Private',
    'profile.language': 'Language',
    'profile.emailNotifications': 'Receive email notifications',
    'profile.saveChanges': 'Save Changes',
    'profile.games': 'game',
    'profile.gamesPlural': 'games',
    'profile.completedGame': 'Completed',
    'profile.addedToList': 'Added',
    'profile.toList': 'to their list',
    'profile.daysAgo': '',
    'profile.days': 'days ago',
    'profile.rating': 'Rating:',
    'profile.hideStats': 'Hide stats',
    'profile.showStats': 'Show stats',
    'profile.noFavoriteGames': 'No favorite games yet',
    
    // Profile Edit
    'profileEdit.title': 'Edit Profile',
    'profileEdit.subtitle': 'Personalize your gaming profile',
    'profileEdit.profilePicture': 'Profile Picture',
    'profileEdit.changePhoto': 'Change Photo',
    'profileEdit.chooseAvatar': 'Choose from our gaming avatars',
    'profileEdit.importImage': 'or import your own image',
    'profileEdit.uploadImage': 'Upload Image',
    'profileEdit.coverPhoto': 'Cover Photo',
    'profileEdit.uploadBanner': 'Upload Banner',
    'profileEdit.chooseTemplate': 'or choose from our templates:',
    'profileEdit.personalInfo': 'Personal Information',
    'profileEdit.biography': 'Biography',
    'profileEdit.biographyPlaceholder': 'Tell us about your favorite games...',
    'profileEdit.location': 'Location',
    'profileEdit.locationPlaceholder': 'Your city or region',
    'profileEdit.customLists': 'Custom Lists',
    'profileEdit.unlimitedLists': 'Unlimited',
    'profileEdit.newList': 'New List',
    'profileEdit.listNamePlaceholder': 'List name...',
    'profileEdit.create': 'Create',
    'profileEdit.noCustomLists': 'No custom lists',
    'profileEdit.createListsDesc': 'Create lists to organize your games',
    'profileEdit.preferences': 'Preferences',
    'profileEdit.profilePrivacy': 'Profile Privacy',
    'profileEdit.public': 'Public',
    'profileEdit.friendsOnly': 'Friends Only',
    'profileEdit.private': 'Private',
    'profileEdit.language': 'Language',
    'profileEdit.emailNotifications': 'Receive email notifications',
    'profileEdit.saveChanges': 'Save Changes',
    
    // Journal
    'journal.title': 'Game Journal',
    'journal.all': 'All',
    'journal.playing': 'Playing',
    'journal.completed': 'Completed',
    'journal.wishlist': 'Wishlist',
    'journal.abandoned': 'Abandoned',
    'journal.onHold': 'On Hold',
    'journal.statistics': 'Statistics',
    'journal.addedOn': 'Added on',
    'journal.lastSession': 'Last session',
    'journal.playtime': 'Playtime',
    'journal.myRating': 'My rating',
    'journal.myReview': 'My review',
    'journal.noGamesFound': 'No games found',
    'journal.startAdding': 'Start adding games to your collection!',
    'journal.gamesByYear': 'Games by Release Year',
    'journal.genreBreakdown': 'Genre Breakdown',
    'journal.platformsUsed': 'Platforms Used',
    'journal.gameStatus': 'Game Status',
    'journal.ratingDistribution': 'Rating Distribution',
    'journal.summary': 'Summary',
    'journal.totalGames': 'Total games',
    'journal.differentGenres': 'Different genres',
    'journal.platformsUsedCount': 'Platforms used',
    'journal.gamesRated': 'Games rated',
    'journal.averageRating': 'Average rating',
    
    // Search
    'search.title': 'Search',
    'search.games': 'Games',
    'search.users': 'Users',
    'search.searchGames': 'Search for a game, developer, genre...',
    'search.searchUsers': 'Search for a user...',
    'search.filters': 'Filters',
    'search.clearAll': 'Clear all',
    'search.relevance': 'Relevance',
    'search.highestRated': 'Highest rated',
    'search.lowestRated': 'Lowest rated',
    'search.newest': 'Newest',
    'search.oldest': 'Oldest',
    'search.mostAnticipated': 'Most anticipated',
    'search.publisher': 'Publisher',
    'search.gameType': 'Game type',
    'search.releaseYear': 'Release year',
    'search.playerCount': 'Player count',
    'search.userRatings': 'User ratings',
    'search.results': 'Results',
    'search.noResults': 'No results for',
    'search.tryOtherKeywords': 'Try other keywords or check spelling.',
    'search.modifyFilters': 'Try modifying your search criteria or filters.',
    'search.noUsersFound': 'No users found for',
    'search.tryOtherUsers': 'Try other keywords or browse friend suggestions.',
    'search.followers': 'followers',
    'search.following': 'following',
    'search.gamesPlayed': 'games played',
    
    // Feed
    'feed.title': 'News Feed',
    'feed.friends': 'Friends',
    'feed.follows': 'Follows',
    'feed.trends': 'Trends',
    'feed.recent': 'Most recent',
    'feed.mostLiked': 'Most liked',
    'feed.mostCommented': 'Most commented',
    'feed.share': 'Share',
    'feed.writeComment': 'Write a comment...',
    'feed.comment': 'Comment',
    'feed.reply': 'Reply',
    'feed.helpful': 'Helpful',
    'feed.noActivity': 'No recent activity',
    'feed.followMore': 'Follow more friends to see their activity here!',
    'feed.noComments': 'No comments yet',
    'feed.ago': '',
    'feed.hours': 'h ago',
    'feed.days': 'd ago',
    'feed.minutes': 'min ago',
    
    // Discover
    'discover.title': 'Discover',
    'discover.topRated': 'Top Rated Games',
    'discover.mostAnticipated': 'Most Anticipated Games',
    'discover.recommended': 'Recommended for you',
    'discover.upcoming': 'Upcoming',
    'discover.topPlayed': 'Top Most Played Games',
    'discover.goodRecommendation': 'Good recommendation',
    'discover.badRecommendation': 'Bad recommendation',
    
    // Premium
    'premium.title': 'Factiony Premium',
    'premium.subtitle': 'Unlock the full potential of your gaming experience',
    'premium.price': '€2.99',
    'premium.perMonth': 'per month (VAT included)',
    'premium.upgrade': 'Upgrade to Premium',
    'premium.referral': 'Referral Program',
    'premium.referralDesc': 'Invite your friends to Factiony and get 1 month Premium free for each group of 3 friends who create accounts!',
    'premium.whatYouGet': 'What does Premium bring you?',
    'premium.detailedRating': 'Detailed game rating',
    'premium.detailedRatingDesc': 'Rate gameplay, graphics, story and music separately',
    'premium.fullCustomization': 'Complete profile customization',
    'premium.fullCustomizationDesc': 'Profile picture, custom banner and exclusive themes',
    'premium.unlimitedLists': 'Unlimited lists',
    'premium.unlimitedListsDesc': 'Create as many lists as you want (vs 2 without Premium)',
    'premium.weeklyNewsletter': 'Weekly newsletter',
    'premium.weeklyNewsletterDesc': 'Receive the latest gaming news and personalized recommendations',
    'premium.supportBuff': 'Support Factiony',
    'premium.supportBuffDesc': 'Help us develop new features and grow the community',
    'premium.adFree': 'Ad-free interface',
    'premium.adFreeDesc': 'Enjoy a pure experience without advertising interruptions',
    'premium.discordAccess': 'Premium Forum Access',
    'premium.discordAccessDesc': 'Join our exclusive forum and discuss with other Premium members',
    'premium.cancelAnytime': 'Cancel anytime',
    'premium.testimonials': 'What our Premium users say',
    'premium.testimonial1': 'Unlimited lists changed the way I organize my collection. I recommend it!',
    'premium.testimonial2': 'The newsletter helps me discover new games every week. Perfect!',
    'premium.testimonialAuthor1': 'GameMaster92',
    'premium.testimonialAuthor2': 'ProGamer',
    'premium.finalizeSubscription': 'Finalize your subscription',
    'premium.referralCode': 'Your referral code:',
    'premium.copy': 'Copy',
    'premium.summary': 'Summary',
    'premium.monthly': 'monthly',
    'premium.total': 'Total',
    'premium.vatIncluded': 'VAT included',
    'premium.cardNumber': 'Card number',
    'premium.expiryDate': 'Expiry date',
    'premium.cardName': 'Name on card',
    'premium.confirmPayment': 'Confirm payment',
    'premium.securePayment': 'Secure payment. Cancel anytime from your profile.',
    'premium.paymentSuccess': 'Simulated payment successful! Welcome to Factiony Premium 🎉',
    
    // Friends
    'friends.title': 'Add Friends',
    'friends.search': 'Search by name or email',
    'friends.searchPlaceholder': 'Username or email...',
    'friends.invite': 'Invite a Friend',
    'friends.inviteDesc': 'Share Factiony with your friends and earn 1 month Premium free for each group of 3 friends!',
    'friends.referralCode': 'Your referral code:',
    'friends.copyLink': 'Copy Link',
    'friends.sendInvite': 'Send Invitation',
    'friends.follow': 'Follow',
    'friends.following': 'Following',
    'friends.discoverFollow': 'Discover and follow other passionate gamers',
    'friends.referralBenefits': 'Referral benefits',
    'friends.benefit1': '1 month Premium free for you (every 3 friends)',
    'friends.benefit2': '1 month Premium free for your friend',
    'friends.benefit3': 'Help Factiony grow',
    'friends.benefit4': 'Share your gaming passion',

    // Games
    'games.rating': 'Rating',
    'games.platforms': 'Platforms',
    'games.publisher': 'Publisher',
    'games.votes': 'votes',
    'games.rateAndReview': 'Rate and review',
    'games.followGame': 'Follow this game',
    'games.yourRating': 'Your rating',
    'games.yourReview': 'Your review...',
    'games.publish': 'Publish',
    'games.buyGame': 'Buy the game',
    'games.buyOn': 'Buy on',
    'games.userReviews': 'User Reviews',
    'games.masterpiece': 'An absolute masterpiece! The story, characters, open world... everything is perfect.',
    'games.agree': 'Totally agree! This game is a masterpiece.',

    // Notifications
    'notifications.title': 'My Notifications',
    'notifications.all': 'All',
    'notifications.likes': 'Likes',
    'notifications.followers': 'Followers',
    'notifications.comments': 'Comments',
    'notifications.noNotifications': 'No notifications',
    'notifications.settings': 'Notification Settings',
    'notifications.newFollowers': 'New followers',
    'notifications.newFollowersDesc': 'When someone follows you',
    'notifications.likesOnReviews': 'Likes on your reviews',
    'notifications.likesOnReviewsDesc': 'When someone likes your reviews',
    'notifications.commentsDesc': 'When someone comments on your reviews',
    'notifications.friendActivity': 'Friend activity',
    'notifications.friendActivityDesc': 'New reviews from your subscriptions',
    'notifications.gameReleases': 'Game releases',
    'notifications.gameReleasesDesc': 'New games and updates',
    'notifications.promotions': 'Promotions',
    'notifications.promotionsDesc': 'Special offers and discounts',
    'notifications.method': 'Notification method',
    'notifications.pushNotifications': 'Push notifications',
    'notifications.emailOnly': 'Email only',

    // Account Settings
    'account.title': 'Account Settings',
    'account.username': 'Username',
    'account.firstName': 'First Name',
    'account.lastName': 'Last Name',
    'account.bio': 'Biography',
    'account.saveChanges': 'Save changes',
    'account.security': 'Security',
    'account.changePassword': 'Change password',
    'account.deleteAccount': 'Delete account',
    'account.updated': 'Information updated!',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.copy': 'Copy',
    'common.search': 'Search',
    'common.loading': 'Loading...',
    'common.language': 'Language',
    'common.french': 'Français',
    'common.english': 'English',
    'common.back': 'Back',
    'common.continue': 'Continue',
    'common.skip': 'Skip this step',
    'common.finish': 'Finish',
    'common.copied': 'Copied!',
    'common.minimum': 'minimum',
    'common.total': 'Total',
    'common.post': 'Post',
    'common.send': 'Send',
    'common.reply': 'Reply',
    'common.sending': 'Sending...',
    'common.confirmDelete': 'Are you sure you want to delete this item?',
    'common.showReplies': 'Show replies',
    'common.hideReplies': 'Hide replies',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    
    // Game Detail Modal
    'game.overview': 'Overview',
    'game.reviews': 'Reviews',
    'game.forum': 'Forum',
    'game.description': 'Description',
    'game.screenshots': 'Screenshots',
    'game.systemRequirements': 'System Requirements',
    'game.minimum': 'Minimum',
    'game.recommended': 'Recommended',
    'game.information': 'Information',
    'game.developer': 'Developer',
    'game.publisher': 'Publisher',
    'game.releaseDate': 'Release Date',
    'game.platforms': 'Platforms',
    'game.metacritic': 'Metacritic',
    'game.playtime': 'Playtime',
    'game.mainStory': 'Main Story',
    'game.completionist': 'Completionist',
    'game.average': 'Average',
    'game.buyGame': 'Buy the game',
    'game.rateAndReview': 'Rate and review',
    'game.followGame': 'Follow this game',
    'game.followed': 'Followed',
    'game.addSession': 'Add session',
    'game.userReviews': 'User Reviews',
    'game.noReviews': 'No reviews yet',
    'game.writeReview': 'Write a review',
    'game.trailers': 'Trailers',
    'game.trailer': 'Trailer',
    'game.coming': 'Coming Soon',
    'game.votes': 'votes',
    'game.anticipating': 'Anticipating',
    'game.anticipated': 'Anticipated',
    'game.anticipationCount': 'people anticipating',
    'game.whyAnticipate': 'Why do you want to play it?',
    'game.whyNotAnticipate': 'Why don\'t you want to play it?',
    'game.anticipationComment': 'Your comment...',
    'game.wantToPlay': 'Can\'t wait to play',
    'game.dontWantToPlay': 'Don\'t think I\'ll play',
    'game.anticipationComments': 'Anticipation Comments',
    'game.forumDiscussion': 'Discussion',
    'game.askQuestion': 'Ask a question',
    'game.shareThoughts': 'Share your thoughts',
    'game.writeComment': 'Write a comment...',
    'game.sortBy': 'Sort by',
    'game.mostRecent': 'Most recent',
    'game.mostPopular': 'Most popular',
    'game.mostLiked': 'Most liked',
    'game.reply': 'Reply',
    'game.replies': 'replies',
    'game.showReplies': 'Show replies',
    'game.hideReplies': 'Hide replies',
    'game.writeReply': 'Write a reply...',
    'game.noForumPosts': 'No discussions yet',
    'game.startDiscussion': 'Be the first to start the discussion!',
    
    // Review Modal
    'review.writeReview': 'Write a review',
    'review.yourReview': 'Your review',
    'review.rating': 'Rating',
    'review.notRated': 'Not rated',
    'review.quickReview': 'Rating only (no written review)',
    'review.rateOnly': 'Rate only',
    'review.shareExperience': 'Share your experience with this game...',
    'review.containsSpoilers': 'This review contains spoilers',
    'review.personalTags': 'Personal tags',
    'review.addTag': 'Add a tag...',
    'review.add': 'Add',
    'review.cancel': 'Cancel',
    'review.publish': 'Publish review',
    'review.share': 'Share',
    'review.shareReview': 'Share Review',
    'review.copyLink': 'Copy Link',
    'review.copied': 'Copied!',
    'review.shareOn': 'Share on',
    
    // Game Session Modal
    'session.newSession': 'New game session',
    'session.date': 'Date',
    'session.duration': 'Duration (minutes)',
    'session.platform': 'Platform',
    'session.progress': 'Progress (%)',
    'session.personalNotes': 'Personal notes',
    'session.impressions': 'Your impressions on this session...',
    'session.addScreenshots': 'Add screenshots',
    'session.save': 'Save',
    
    // Game Card
    'gameCard.addToList': 'Add to list',
    'gameCard.removeFromList': 'Remove from list'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export { LanguageContext };

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<'fr' | 'en'>('fr');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('factiony-language') as 'fr' | 'en';
    if (savedLanguage) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: 'fr' | 'en') => {
    setLanguage(lang);
    localStorage.setItem('factiony-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['fr']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};